import type { ElementType } from 'react';
import {
  Activity,
  AlarmCheck,
  AlertTriangle,
  Ambulance,
  Archive,
  Award,
  BarChart3,
  Bell,
  Calendar,
  ClipboardCheck,
  ClipboardList,
  ClipboardSignature,
  Clock4,
  CreditCard,
  DollarSign,
  FileBarChart,
  FileText,
  HeartPulse,
  LayoutDashboard,
  LifeBuoy,
  Link,
  LogOut,
  MapPin,
  MessageSquare,
  MonitorSmartphone,
  Moon,
  Package,
  Pill,
  Printer,
  Receipt,
  Search,
  Settings,
  ShieldCheck,
  ShoppingBag,
  SlidersHorizontal,
  Stethoscope,
  Store,
  Table,
  Target,
  TimerReset,
  Truck,
  TrendingUp,
  UserPlus,
  Users,
  Wallet,
  Wrench,
  Ban,
  User,
  ShoppingCart,
  CircleUser,
} from 'lucide-react';

export const ICON_LIBRARY = {
  activity: Activity,
  alarmCheck: AlarmCheck,
  alertTriangle: AlertTriangle,
  ambulance: Ambulance,
  archive: Archive,
  award: Award,
  barChart3: BarChart3,
  bell: Bell,
  calendar: Calendar,
  clipboardCheck: ClipboardCheck,
  clipboardList: ClipboardList,
  clipboardSignature: ClipboardSignature,
  clock: Clock4,
  creditCard: CreditCard,
  dollarSign: DollarSign,
  fileBarChart: FileBarChart,
  fileText: FileText,
  heartPulse: HeartPulse,
  layoutDashboard: LayoutDashboard,
  lifeBuoy: LifeBuoy,
  link: Link,
  logOut: LogOut,
  mapPin: MapPin,
  messageSquare: MessageSquare,
  monitor: MonitorSmartphone,
  moon: Moon,
  package: Package,
  pill: Pill,
  printer: Printer,
  receipt: Receipt,
  search: Search,
  settings: Settings,
  shieldCheck: ShieldCheck,
  shoppingBag: ShoppingBag,
  slidersHorizontal: SlidersHorizontal,
  stethoscope: Stethoscope,
  store: Store,
  table: Table,
  target: Target,
  timerReset: TimerReset,
  truck: Truck,
  trendingUp: TrendingUp,
  userPlus: UserPlus,
  users: Users,
  wallet: Wallet,
  wrench: Wrench,
  none: Ban,
  user: User,
  shoppingCart: ShoppingCart,
  circleUser: CircleUser,
};

export const ICON_OPTIONS = [
  { value: 'none', label: 'Aucune', icon: Ban },
  { value: 'activity', label: 'Activité', icon: Activity },
  { value: 'alarmCheck', label: 'Alarmes validées', icon: AlarmCheck },
  { value: 'alertTriangle', label: 'Alerte', icon: AlertTriangle },
  { value: 'ambulance', label: 'Ambulance', icon: Ambulance },
  { value: 'archive', label: 'Archive', icon: Archive },
  { value: 'award', label: 'Badge', icon: Award },
  { value: 'barChart3', label: 'Barres', icon: BarChart3 },
  { value: 'bell', label: 'Notifications', icon: Bell },
  { value: 'calendar', label: 'Calendrier', icon: Calendar },
  { value: 'clipboardCheck', label: 'Todo validé', icon: ClipboardCheck },
  { value: 'clipboardList', label: 'Liste', icon: ClipboardList },
  { value: 'clipboardSignature', label: 'Signature', icon: ClipboardSignature },
  { value: 'clock', label: 'Horloge', icon: Clock4 },
  { value: 'creditCard', label: 'Carte bancaire', icon: CreditCard },
  { value: 'dollarSign', label: 'Finance', icon: DollarSign },
  { value: 'fileBarChart', label: 'Rapport', icon: FileBarChart },
  { value: 'fileText', label: 'Document', icon: FileText },
  { value: 'heartPulse', label: 'Santé', icon: HeartPulse },
  { value: 'layoutDashboard', label: 'Dashboard', icon: LayoutDashboard },
  { value: 'lifeBuoy', label: 'Assistance', icon: LifeBuoy },
  { value: 'link', label: 'Lien', icon: Link },
  { value: 'logOut', label: 'Déconnexion', icon: LogOut },
  { value: 'mapPin', label: 'Localisation', icon: MapPin },
  { value: 'messageSquare', label: 'Messages', icon: MessageSquare },
  { value: 'monitor', label: 'Monitoring', icon: MonitorSmartphone },
  { value: 'moon', label: 'Sombre', icon: Moon },
  { value: 'package', label: 'Colis', icon: Package },
  { value: 'pill', label: 'Médicament', icon: Pill },
  { value: 'printer', label: 'Imprimante', icon: Printer },
  { value: 'receipt', label: 'Reçu', icon: Receipt },
  { value: 'search', label: 'Recherche', icon: Search },
  { value: 'settings', label: 'Réglages', icon: Settings },
  { value: 'shieldCheck', label: 'Sécurité', icon: ShieldCheck },
  { value: 'shoppingBag', label: 'Commandes', icon: ShoppingBag },
  { value: 'slidersHorizontal', label: 'Paramètres', icon: SlidersHorizontal },
  { value: 'stethoscope', label: 'Stéthoscope', icon: Stethoscope },
  { value: 'store', label: 'Magasin', icon: Store },
  { value: 'table', label: 'Tableau', icon: Table },
  { value: 'target', label: 'Objectif', icon: Target },
  { value: 'timerReset', label: 'Timer', icon: TimerReset },
  { value: 'truck', label: 'Livraison', icon: Truck },
  { value: 'trendingUp', label: 'Croissance', icon: TrendingUp },
  { value: 'userPlus', label: 'Nouvel utilisateur', icon: UserPlus },
  { value: 'users', label: 'Utilisateurs', icon: Users },
  { value: 'wallet', label: 'Portefeuille', icon: Wallet },
  { value: 'wrench', label: 'Maintenance', icon: Wrench },
  { value: 'user', label: 'Utilisateur', icon: User },
  { value: 'shoppingCart', label: 'Panier', icon: ShoppingCart },
  { value: 'circleUser', label: 'Profil', icon: CircleUser },
];

export type IconKey = keyof typeof ICON_LIBRARY;

export const ICON_ALIASES: Record<string, IconKey> = {
  'layout-dashboard': 'layoutDashboard',
  'user-plus': 'userPlus',
  'file-text': 'fileText',
  'clipboard-list': 'clipboardList',
  'credit-card': 'creditCard',
  'dollar-sign': 'dollarSign',
  'shopping-bag': 'shoppingBag',
  'sliders-horizontal': 'slidersHorizontal',
  'stethoscope': 'stethoscope',
  'table': 'table',
  'target': 'target',
  'truck': 'truck',
  'trending-up': 'trendingUp',
  'map-pin': 'mapPin',
  'message-square': 'messageSquare',
  'monitor-smartphone': 'monitor',
  'bell': 'bell',
  'calendar': 'calendar',
  'search': 'search',
  'log-out': 'logOut',
  'moon': 'moon',
  'users': 'users',
  'package': 'package',
  'pill': 'pill',
  'store': 'store',
  'heart-pulse': 'heartPulse',
  'clipboard-check': 'clipboardCheck',
  'clipboard-signature': 'clipboardSignature',
  'award': 'award',
  'file-bar-chart': 'fileBarChart',
  'timer-reset': 'timerReset',
  'wallet': 'wallet',
  'life-buoy': 'lifeBuoy',
};

const ICON_RECORD = ICON_LIBRARY as Record<string, ElementType>;

export const normalizeIconKey = (value?: string): IconKey => {
  if (!value) {
    return 'barChart3';
  }
  const trimmed = value.trim();
  if (ICON_RECORD[trimmed]) {
    return trimmed as IconKey;
  }
  const alias = ICON_ALIASES[trimmed];
  if (alias && ICON_RECORD[alias]) {
    return alias;
  }
  return 'barChart3';
};
